# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
    project 'Practitioner.xcodeproj'


target 'Practitioner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practitioner
	
   pod 'NVActivityIndicatorView', '5.0.0'

  target 'PractitionerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PractitionerUITests' do
    # Pods for testing
  end

end

# Apple M1 Chip integration helper
post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
end
